### ISSUE TITLE
Extensions: include Replace Activities Label by Leleat

### ISSUE THREAD

**Issue by cassidyjames** [ublue-os/beyond#10]
This extension was developed to test a design idea for GNOME Shell.

https://extensions.gnome.org/extension/5706/replace-activities-label/

**Comment by IlChitarrista** [comment]
# Reflexion

Hello, this is interesting although, as others have noticed, it might not be descriptive enough for someone not using Gnome as their primary desktop.

## The devil is in the details

This extension experimentally supports the usage of an Animation File which might make this a tad bit more flavored.

It can also Hide the App Menu which is something that has already been tested for the Focus Indicator that was eventually not merged for reasons currently unknown to me.
I like the idea of being able to Hide this menu but it might damage the experience for Mouse Centered use cases.

## Conclusion

We should also reflect on whether or not the Focus Indicator might actually be a good inclusion as the feature set partly overlaps and that extension shows, in my opinion, a clearer improvement in usability.

**Comment by cassidyjames** [comment]
>It might not be descriptive enough for someone not using Gnome as their primary desktop.

That's the entire point of trialing things here, in an experimental place, to see how people get on with it.

>It can also Hide the App Menu which is something that has already been tested for the Focus Indicator that was eventually not merged for reasons currently unknown to me.

This will likely be default in GNOME 45. It was tested late in the GNOME 44 cycle and we decided against making that large UI change alone without testing more options for the Activities button itself.

For context, the point of Beyond is that I'm involved in GNOME design discussions, and am using this as a test bed for trying out ideas that come up within the upstream GNOME discussions. We can iterate fast here and change them much more easily than GNOME can do (where they have to worry about release screenshots and a more stable overall experience).

Think of Beyond as an A/B testing ground for GNOME. :)

**Comment by IlChitarrista** [comment]
Thank you for the clarification, I'm testing the extension out, it's a good inclusion. :)
The Focus Indicator is too a good extension.

**Comment by cassidyjames** [comment]
Superseded by #87
