### ISSUE TITLE
Set default dash contents

### ISSUE THREAD

**Issue by cassidyjames** [ublue-os/beyond#35]
I think I'd go lightweight with:

- Files
- Web
- Settings
- Software

I'd be curious to see what GNOME OS ships ootb in the dash, though.

**Comment by castrojo** [comment]
I just need the org.gnome.blah names for Settings and Software, which I can't seem to find.

**Comment by cassidyjames** [comment]
@castrojo you can `gsettings get org.gnome.shell favorite-apps` to read your current setting which is useful for this sort of thing. 😁

Looks like you want `org.gnome.Settings.desktop` and `org.gnome.Software.desktop`
