### ISSUE TITLE
Web app support

### ISSUE THREAD

**Issue by cassidyjames** [ublue-os/beyond#47]
This might end up being a meta-issue to track individual issues, depending on the scope of work. But we'd need to make sure we have GNOME Software with all the correct flags enabled, plus metadata for web apps for GNOME Software (like [we have in Endless OS](https://github.com/endlessm/gnome-software-data)) at the very least.

**Comment by castrojo** [comment]
Some more info here from our research: https://github.com/ublue-os/bluefin/issues/43

We have a ublue-os COPR, and hoping we can get gnome-software with the right flags in there when we can.

**Comment by KyleGospo** [comment]
You can use gnome-software from the ublue copr: https://github.com/ublue-os/bluefin/issues/43#issuecomment-1579339125

**Comment by castrojo** [comment]
Thanks for your help on this Kyle! It's landed on the image now, no idea how to use it but I guess we'll find out!
