### ISSUE TITLE
 modern CLI tools

### ISSUE THREAD

**Issue by leonardobetti** [ublue-os/beyond#55]
Hi all, I've got a few suggestions for Beyond. By the way, I'm not sure if this is the right place, so apologies to Cass and Jorge if it's not. How about adding some modern CLI tools to enhance the experience using the terminal?
- [micro](https://github.com/zyedidia/micro) text editor. It's a proper gem, much smoother than Nano. Micro offers common keyboard shortcuts, a touch of mouse support (for those who like it), and syntax highlighting. It's more user-friendly compared to Nano, Vi, Emacs, and the likes.
- [bat](https://github.com/sharkdp/bat): a clever clone of the "cat" command, with syntax highlighting and Git integration
 - [exa](https://github.com/ogham/exa): replacement for the "ls" command, Exa lists files and directories with fancy colors. It's visually appealing and easier to read.
- [fd](https://github.com/sharkdp/fd): lightning-fast and user-friendly alternative to "find" simplifies file searches
- [bottom](https://github.com/ClementTsang/bottom): replacement for "htop,", bottom offers a fresh and more intuitive way to monitor system resources
Also, if these suggestions are not within the scope of the project please feel free to disregard them.

**Comment by cassidyjames** [comment]
@leonardobetti thanks for your suggestions! At the moment, my focus with Beyond is really on the graphical user experience; some of these utilities might be attractive to [Bluefin-dx](https://github.com/ublue-os/bluefin#bluefin-dx---the-bluefin-developer-experience) though, so it might make sense to open this there.
