### ISSUE TITLE
Flatpak: Include GNOME Web 

### ISSUE THREAD

**Issue by cassidyjames** [ublue-os/beyond#6]
GNOME Web should be installed as a system Flatpak, replacing Firefox.

**Comment by castrojo** [comment]
Notes for ourselves from Marco: 

This is how you set the default for all the packages (we won't use this, just for reference): 

- https://github.com/ublue-os/yafti/blob/main/tests/example-system.yml#L38-L40

And here's how we do it per package, which is how we'll do this: 

- https://github.com/ublue-os/yafti/blob/main/tests/example-system.yml#L46-L49
