### ISSUE TITLE
Automate grabbing the latest Inter beta release?

### ISSUE THREAD

**Issue by cassidyjames** [ublue-os/beyond#61]
This seems like something entirely automatable... or maybe we don't need to track the beta releases so closely. 🤷🏻

**Comment by castrojo** [comment]
Note that we want the prerelease version and not the one tagged as stable, so not as stackoverflowable as I thought it would be. 😄

**Comment by cassidyjames** [comment]
@castrojo I StackOverlowed even harder and found you can:

```shell
curl -s https://api.github.com/repos/rsms/inter/releases | jq -r 'map(select(.prerelease)) | .[0].tag_name'
```

…which does give me `v4.0-beta9e`. Then you could use [fetch-github-release-asset](https://github.com/marketplace/actions/fetch-github-release-asset) and pass that in to get the release asset… then unzip it and put the right files in the right places, e.g. `cp Inter.ttc *.ttf …`. 😄

**Comment by marcoceppi** [comment]
Did a little more code-golf and got it as a oneliner in the container file. I'll post a PR in a few mins
