### ISSUE TITLE
Extensions: include Dash to Dock

### ISSUE THREAD

**Issue by cassidyjames** [ublue-os/beyond#8]
No idea how to implement this. Ideally I could also provide a specific configuration, because I don't love the default.

https://extensions.gnome.org/extension/307/dash-to-dock/

**Comment by cassidyjames** [comment]
An alternative would be [Dock from Dash](https://extensions.gnome.org/extension/4703/dock-from-dash/) which is close, but I'd want to test its multi-display behavior first.

**Comment by castrojo** [comment]
I've added dash-to-dock as a system package since it's in fedora already, however it's still applying the bluefin settings to it so I'll reset that next.

I've also included dock-from-dash in the justfile but I need to automate part of that so this isn't solved yet.

**Comment by cassidyjames** [comment]
@castrojo I just tested dock-from-dash, and it is broken on my multi-display setup. Looks like I'll want to ship a custom config for Dash to Dock instead!
