### ISSUE TITLE
Use Inter font 

### ISSUE THREAD

**Issue by cassidyjames** [ublue-os/beyond#9]
This might have to be packaged or something, but the default UI font should be set to `Inter 11` system-wide.

I lean towards using the Inter 4 beta since it has some pretty substantial improvements.

https://github.com/rsms/inter/releases

**Comment by castrojo** [comment]
This is done, I'm assuming we're leaving "Mono" and "Legacy Window Titles" as default?

**Comment by cassidyjames** [comment]
Yeah that's fine! Fixed in aa38a0d5cdf15e63e44ad01f9ca747d7be307676
